name: Sync dependencies for GA

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * *'
jobs:
  sync:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        os: [macos-12, macos-13]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
      - name: sync
        run: bash ./.github/scripts/sync.sh
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
