name: 'Update and Build Formulae'
on:
  push:
  schedule:
    - cron:  '0 0 * * *'
  repository_dispatch:
jobs:
  supported:
    if: "!contains(github.event.head_commit.message, 'skip_build')"
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        php-version:
          - 'php'
          - 'php@5.6'
          - 'php@7.0'
          - 'php@7.1'
          - 'php@7.2'
          - 'php@7.3'
          - 'php@8.0'
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: sh ./.github/scripts/build.sh
      env:        
        GITHUB_ACTIONS: true        
        GITHUB_MESSAGE: ${{ github.event.head_commit.message }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GIT_URL: ${{ github.event.repository.html_url }}
        HOMEBREW_BINTRAY_URL: https://dl.bintray.com/${{ github.repository_owner }}/php
        HOMEBREW_BINTRAY_USER: ${{ github.repository_owner }}
        HOMEBREW_BINTRAY_REPO: php
        HOMEBREW_BINTRAY_EMAIL: ${{ secrets.email }}
        HOMEBREW_BINTRAY_KEY: ${{ secrets.bintray_key }}
        HOMEBREW_NO_ANALYTICS: 1
        HOMEBREW_NO_AUTO_UPDATE: 1
        HOMEBREW_NO_INSTALL_CLEANUP: 1        
        PHP_VERSION: ${{ matrix.php-version }}
      continue-on-error: true
