name: 'Update and Build Formulae'
on:
  push:
  schedule:
    - cron:  '0 0 * * *'
  repository_dispatch:
jobs:
  sync:
    if: "!contains(github.event.head_commit.message, 'skip-sync')"
    runs-on: ${{ matrix.os-version }}
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        os-version: [macos-10.15, macos-11.0]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: sync
        run: sh ./.github/scripts/sync.sh
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  supported:
    needs: sync
    if: "!contains(github.event.head_commit.message, 'skip-build')"
    runs-on: ${{ matrix.os-version }}
    strategy:
      fail-fast: false
      matrix:
        os-version: [macos-10.15]
        php-version:
          - 'php'
          - 'php@5.6'
          - 'php@7.0'
          - 'php@7.1'
          - 'php@7.2'
          - 'php@7.3'
          - 'php@7.4'
          - 'php@8.1'
        include:
          - php-version: 'php@8.1'
            os-version: 'macos-11.0'
    steps:
    - uses: actions/checkout@v2
      with:
        ref: master
    - name: build
      id: build
      run: sh ./.github/scripts/build.sh
      env:        
        GITHUB_ACTIONS: true        
        GITHUB_MESSAGE: ${{ github.event.head_commit.message }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GIT_URL: ${{ github.event.repository.html_url }}
        HOMEBREW_BINTRAY_URL: https://dl.bintray.com/${{ github.repository_owner }}/php
        HOMEBREW_BINTRAY_USER: ${{ github.repository_owner }}
        HOMEBREW_BINTRAY_REPO: php
        HOMEBREW_BINTRAY_EMAIL: ${{ secrets.email }}
        HOMEBREW_BINTRAY_KEY: ${{ secrets.bintray_key }}
        HOMEBREW_NO_ANALYTICS: 1
        HOMEBREW_NO_AUTO_UPDATE: 1
        HOMEBREW_NO_INSTALL_CLEANUP: 1        
        PHP_VERSION: ${{ matrix.php-version }}
        DARWIN_VERSION: ${{ matrix.os-version }}
      continue-on-error: true
    - name: Upload Artifact
      if: steps.build.outputs.build == 'true'
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.php-version }}
        path: ./*.tar.gz
